services:
  postgresql:
    image: postgres:14-alpine
    container_name: dbmicro
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
    - "8113"
    command: -p 8113
